[framework]
name = "Gemini"
authors = ["Brian Hauer <bhauer@techempower.com>", "Mike Smith <msmith@techempower.com>"]
github = "https://github.com/TechEmpower/gemini"

[default]
urls.json = "/json"
urls.plaintext = "/plaintext"
approach = "Realistic"
classification = "Fullstack"
platform = "Servlet"
webserver = "Resin"
os = "Linux"
versus = "servlet"

[mysql]
urls.db = "/db"
urls.query = "/query?queries="
urls.cached_query = "/cached_query?queries="
urls.fortune = "/fortunes"
urls.update = "/update?queries="
port = 8080
approach = "Realistic"
classification = "Fullstack"
database = "MySQL"
orm = "Micro"
platform = "Servlet"
webserver = "Resin"
os = "Linux"
database_os = "Linux"
versus = "servlet"
tags = ["broken"]

[postgres]
urls.db = "/db"
urls.query = "/query?queries="
urls.cached_query = "/cached_query?queries="
urls.fortune = "/fortunes"
urls.update = "/update?queries="
port = 8080
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
orm = "Micro"
platform = "Servlet"
webserver = "Resin"
os = "Linux"
database_os = "Linux"
database_port = 5432
versus = "servlet"
